// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2019TourneyRoster.DAL;

namespace _2019TourneyRoster.Migrations
{
    [DbContext(typeof(TourneyContext))]
    partial class TourneyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_2019TourneyRoster.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShirtSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamRosterID")
                        .HasColumnType("int");

                    b.HasKey("PlayerID");

                    b.HasIndex("TeamRosterID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("_2019TourneyRoster.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamRosterID")
                        .HasColumnType("int");

                    b.HasKey("TeamID");

                    b.HasIndex("TeamRosterID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("_2019TourneyRoster.Models.TeamRoster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PlayerID")
                        .HasColumnType("int");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("TeamRosters");
                });

            modelBuilder.Entity("_2019TourneyRoster.Models.Player", b =>
                {
                    b.HasOne("_2019TourneyRoster.Models.TeamRoster", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamRosterID");
                });

            modelBuilder.Entity("_2019TourneyRoster.Models.Team", b =>
                {
                    b.HasOne("_2019TourneyRoster.Models.TeamRoster", null)
                        .WithMany("Teams")
                        .HasForeignKey("TeamRosterID");
                });
#pragma warning restore 612, 618
        }
    }
}
